/**
  * Copyright 2017 sesquipedalian.dev@gmail.com
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  * http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */
package org.sesquipedalian_dev.scala2DGaming.entities

import org.sesquipedalian_dev.scala2DGaming.graphics.{HasWorldSpriteRendering, WorldSpritesRenderer}

case class Location(
  x: Float,
  y: Float
)

case class WorldLoc(
  location: Location,
  traversable: Boolean,
  textureFile: String,
  var textureIndex: Option[Int] = None
)

class WorldMap(worldSize: Location) extends HasWorldSpriteRendering {
  var worldLocations: Map[Location, WorldLoc] = Map()

  override def render(worldSpritesRenderer: WorldSpritesRenderer): Unit = {
    for {
      x <- 0 to worldSize.x.toInt
      y <- 0 to worldSize.y.toInt
      location <- worldLocations.get(Location(x,y))
    } {
      if(location.textureIndex.isEmpty) {
        worldSpritesRenderer.textureArray.foreach(ta => {
          val currentLoc = ta.textureFiles.indexOf(location.textureFile)
          if(currentLoc == -1) {
            location.textureIndex = ta.addTextureResource(location.textureFile)
          } else {
            location.textureIndex = Some(currentLoc)
          }
        })
      }
      worldSpritesRenderer.drawAGuyWorld(x, y, location.textureIndex.get)
    }
  }

  def initTestData(): Unit = {
    val texFiles: List[String] = List(
      "/textures/concrete_wall.bmp",  // 0
      "/textures/Fence.bmp",          // 1
      "/textures/grass.bmp",          // 2
      "/textures/gun.bmp",            // 3
      "/textures/sand.bmp",           // 4
      "/textures/wood_floor.bmp"      // 5
    )

    val locationToTexIndex = List(
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      // (2, true)(3, true) - THE REAL STUFF STARTS
      (4, true), (4, true), (1, false), (2, true), (2, true), (0, false), (0, false), (0, false), (0, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (4, true), (4, true), (4, true), (0, false), (5, true), (5, true), (5, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (4, true), (4, true), (4, true), (0, false), (5, true), (5, true), (5, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (4, true), (4, true), (4, true), (0, false), (5, true), (5, true), (5, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (4, true), (4, true), (4, true), (0, false), (5, true), (5, true), (5, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (0, false), (0, false), (0, false), (0, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      // (3, true)(0, false) - back to boring
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true),
      (4, true), (4, true), (1, false), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true), (2, true)
    )

    worldLocations = (for {
      x <- 0 to worldSize.x.toInt
      y <- 0 to worldSize.y.toInt
      (index, traversable) <- locationToTexIndex.drop(x + (y * worldSize.y.toInt)).headOption
      texFile <- texFiles.drop(index).headOption
    } yield {
      WorldLoc(Location(x, y), traversable = traversable, texFile)
    }).map(p => p.location -> p).toMap
  }
}
